# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Emilien Dupont
tagline:          Machine Learning
description:      Machine Learning
url:              https://emiliendupont.github.io
baseurl:
paginate:         5
name:             Emilien Dupont

twitter_name:     emidup
github_name:      EmilienDupont
linkedin_name:    emiliendupont
