# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Emilien Dupont
tagline:          Machine Learning
description:      Machine Learning
url:              https://emiliendupont.github.io
baseurl:
paginate:         5
name:             Emilien Dupont

twitter:
  username:       emidup
  url:            https://twitter.com/emidup
