# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Emilien Dupont
tagline:          Deep Learning is deep learning
description:      Hello at <a href="https://github.com/EmilienDupont" target="_blank">@hola</a>.
url:              https://emiliendupont.github.io
baseurl:
paginate:         5
name:             Emilien Dupont

twitter:
  username:       emidup
  url:            https://twitter.com/emidup
