# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# 2.5. This is required for github pages
remote_theme: daviddarnes/alembic

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: emidup # jekyll-seo-tag > Owners twitter username
author: EmilienDupont # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Emilien Dupont # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/emidup
    - https://www.linkedin.com/in/emiliendupont
    - https://github.com/EmilienDupont
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: # Needed for Siteleaf
    output: true
    description: "" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Emilien Dupont" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/whale-emoji.png" # Site logo, also used in jekyll-seo-tag
description: "Machine Learning" # Site description and default description, also used in jekyll-seo-tag
url: "https://emiliendupont.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/EmilienDupont/emiliendupont.github.io"
email: "emilien.dupont@stats.ox.ac.uk"
disqus: "emiliendupont" # Blog post comments, uncomment the option and set the site ID from your Disqus account
google_analytics: 'UA-109900176-1'
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  160: '/assets/logos/whale-emoji.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Resume
  url: /resume/
- title: Publications
  url: /publications/
- title: Blog
  url: /blog/
- title: Visualizations
  url: https://observablehq.com/@emiliendupont

navigation_footer:
- title: Emilien Dupont
  url: https://emiliendupont.github.io

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/emidup
  LinkedIn: https://www.linkedin.com/in/emiliendupont
  GitHub: https://github.com/EmilienDupont
  link: https://emiliendupont.github.io
  RSS: /feed.xml
