# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Emilien Dupont
tagline:          'Yolo'
description:      'Hello at <a href="https://github.com/EmilienDupont" target="_blank">@hola</a>.'
url:              http://emiliendupont.github.io
baseurl:          /

author:
  name:           'Emilien Dupont'
  url:            https://emiliendupont.github.io

paginate:         5

twitter:
  username:           emidup
  url:                https://twitter.com/emidup
